---
apiVersion: v1
kind: Template
metadata:
  name: playbook-dispatcher-stage-smoke-tests
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: playbook-dispatcher-stage-smoke-tests-${IMAGE_TAG}-${UID}
    annotations:
      "ignore-check.kube-linter.io/no-liveness-probe": "probes not required on Job pods"
      "ignore-check.kube-linter.io/no-readiness-probe": "probes not required on Job pods"
  spec:
    appName: playbook-dispatcher-backend
    testing:
      iqe:
        debug: false
        dynaconfEnvName: "stage_post_deploy"
        filter: ""
        marker: "playbook_dispatcher_stage_smoke)"
        plugins: "playbook_dispatcher"
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: UID
  description: "Unique CJI name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
