{
 "title": "Playbook Dispatcher",
 "tags": [
  "platform-health",
  "playbook-dispatcher"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability SLO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (sum(increase(echo_http_requests_total{status=\"5xx\", service=\"playbook-dispatcher-api\"}[$__range:1m])) / sum(increase(echo_http_requests_total{service=\"playbook-dispatcher-api\"}[$__range:1m])))",
     "legendFormat": "Ratio of successful requests"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{group=\"playbook-dispatcher\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(echo_http_request_duration_seconds_bucket{service=\"playbook-dispatcher-api\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(echo_http_requests_total{service=\"playbook-dispatcher-api\"}[1m])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(response_consumer_error_total{service=\"playbook-dispatcher-response-consumer\"}[1m])) by (type)",
       "legendFormat": "consumer error: {{type}}"
      },
      {
       "expr": "sum(increase(response_consumer_validation_failure_total{service=\"playbook-dispatcher-response-consumer\"}[1m])) by (type)",
       "legendFormat": "consumer failure: {{type}}"
      },
      {
       "expr": "sum(increase(validator_failure_total{service=\"playbook-dispatcher-validator\"}[1m]))",
       "legendFormat": "validator failure"
      },
      {
       "expr": "sum(increase(validator_error_total{service=\"playbook-dispatcher-validator\"}[1m])) by (phase)",
       "legendFormat": "validator error: {{phase}}"
      }
     ]
    },
    {
     "title": "Connector latency",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(client_request_duration_seconds_bucket{service=\"playbook-dispatcher-api\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Connector errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(client_request_duration_seconds_count{service=\"playbook-dispatcher-api\", result!~\"2.*\"}[1m])) by (component)",
       "legendFormat": "{{component}}"
      }
     ]
    },
    {
     "title": "RDS storage usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rdsosmetrics_fileSys_usedPercent{mount_point=\"/rdsdbdata\", exported_instance=~\"playbook-dispatcher-.*\"}",
       "legendFormat": "{{exported_instance}}"
      }
     ]
    }
   ]
  }
 ]
}