apiVersion: v1
kind: Template
metadata:
  name: playbook-dispatcher-psk-secret
objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: auth-psk-${APP_NAME}
  stringData:
    key: ${PSK}

parameters:
- name: APP_NAME
  value: test
- name: PSK
  value: test
