apiVersion: v1
kind: Template
metadata:
  name: playbook-dispatcher-psk-secret
objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: auth-psk-remediations
  stringData:
    key: ${KEY_REMEDIATIONS}

- apiVersion: v1
  kind: Secret
  metadata:
    name: auth-psk-config-manager
  stringData:
    key: ${KEY_CONFIG_MANAGER}

- apiVersion: v1
  kind: Secret
  metadata:
    name: client-psk-cloud-connector
  stringData:
    client-id: ${ID_CLOUD_CONNECTOR}
    client-psk: ${KEY_CLOUD_CONNECTOR}

parameters:
- name: KEY_REMEDIATIONS
  value: PuqrzbBNxz
- name: KEY_CONFIG_MANAGER
  value: FLYdxYZGpq
- name: ID_CLOUD_CONNECTOR
  value: playbook-dispatcher
- name: KEY_CLOUD_CONNECTOR
  value: cloud_connector
