apiVersion: v1
kind: Template
metadata:
  name: playbook-dispatcher
objects:

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: playbook-dispatcher
      pod: playbook-dispatcher-validator
    name: playbook-dispatcher-validator
  spec:
    replicas: ${{REPLICAS_VALIDATOR}}
    selector:
      matchLabels:
        app: playbook-dispatcher
        pod: playbook-dispatcher-validator
    template:
      metadata:
        labels:
          app: playbook-dispatcher
          pod: playbook-dispatcher-validator
      spec:
        containers:
        - args:
          - run
          - -m
          - validator
          env:
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: CLOWDER_ENABLED
            value: "false"
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: ${KAFKA_BOOTSTRAP_HOST}
          - name: METRICS_PORT
            value: "9000"
          image: ${IMAGE}:${IMAGE_TAG}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /live
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: playbook-dispatcher-validator
          ports:
          - containerPort: 9000
            name: metrics
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: 250m
              memory: 256Mi
        imagePullSecrets:
        - name: quay-cloudservices-pull

parameters:
- name: IMAGE_TAG
  required: true
- name: IMAGE
  value: quay.io/cloudservices/playbook-dispatcher

- name: LOG_LEVEL
  value: INFO
- name: CPU_LIMIT
  value: 500m
- name: MEMORY_LIMIT
  value: 512Mi

- name: REPLICAS_API
  value: "1"
- name: REPLICAS_RESPONSE_CONSUMER
  value: "1"
- name: REPLICAS_VALIDATOR
  value: "1"

- name: DB_SSLMODE
  value: verify-full

- name: CLOUD_CONNECTOR_IMPL
  value: mock
- name: CLOUD_CONNECTOR_HOST
  value: mock

- name: KAFKA_BOOTSTRAP_HOST
  required: true
- name: RETURN_URL
  required: true
