// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package public

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List hosts involved in Playbook runs
	// (GET /api/playbook-dispatcher/v1/run_hosts)
	ApiRunHostsList(ctx echo.Context, params ApiRunHostsListParams) error
	// List Playbook runs
	// (GET /api/playbook-dispatcher/v1/runs)
	ApiRunsList(ctx echo.Context, params ApiRunsListParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ApiRunHostsList converts echo context to params.
func (w *ServerInterfaceWrapper) ApiRunHostsList(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ApiRunHostsListParams
	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("deepObject", true, false, "filter", ctx.QueryParams(), &params.Filter, runtime.BindQueryParameterOptions{Type: "object", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter filter: %s", err))
	}

	// ------------- Optional query parameter "fields" -------------

	err = runtime.BindQueryParameterWithOptions("deepObject", true, false, "fields", ctx.QueryParams(), &params.Fields, runtime.BindQueryParameterOptions{Type: "object", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fields: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiRunHostsList(ctx, params)
	return err
}

// ApiRunsList converts echo context to params.
func (w *ServerInterfaceWrapper) ApiRunsList(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ApiRunsListParams
	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameterWithOptions("deepObject", true, false, "filter", ctx.QueryParams(), &params.Filter, runtime.BindQueryParameterOptions{Type: "object", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter filter: %s", err))
	}

	// ------------- Optional query parameter "fields" -------------

	err = runtime.BindQueryParameterWithOptions("deepObject", true, false, "fields", ctx.QueryParams(), &params.Fields, runtime.BindQueryParameterOptions{Type: "object", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fields: %s", err))
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_by", ctx.QueryParams(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort_by: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApiRunsList(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/playbook-dispatcher/v1/run_hosts", wrapper.ApiRunHostsList, options.OperationMiddlewares["api.run.hosts.list"]...)
	router.GET(options.BaseURL+"/api/playbook-dispatcher/v1/runs", wrapper.ApiRunsList, options.OperationMiddlewares["api.runs.list"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Frdbxu5Ef9XCLYPLaBIcpI7XPVUx3dBgvqSwDm3BySGQy1HEhMuueGHbDXQ/14Mud9LaeXc9ZB7s7gz",
	"w+F88TdDf6GZzgutQDlLF19owQzLwYEJvy5FLhz+wcFmRhROaEUX9Gd2L3KfE+XzJRiiV8SA9dJZ4jQx",
	"4LxRdEIFkn72YHZ0QhXLgS6oDAIn1GYbyFmUvGJeOrr4bj6heRRMF4/n+Euo+OtsQt2uQH6hHKzB0P1+",
	"Ql+vVhYS2r1UXGTMgSVuA8Q6ZpxQa1JoK5AC1cUPQTNiQDIntoCa4ypaQ4IDYsEhpXCQoyDmSM5ctmlY",
	"D5xQR62SR2yfaZ4805VXL7R1zwVIbodH+xFWQoElq/AddV5CaXDgRKignQFbaGVh+h69APeF1BzowhkP",
	"aZWjtI7KhdEFGCcgKsFc9yDv6EbbcEjHnEdW4xW9mdBgLiQFhYes6fBzi9o6rj2uS6E+2WDJLSinze5W",
	"cJRTmsY6I9Sa7usFZgzbBUuVC3r5ETKHFNbtJK5wgOJ1vVobVDowQ4OeS6nvLFlpQ1aBBCNlySxwohXZ",
	"MiO0tyQzAj+xU80Z9jpszs5hF1/oXw2s6IL+Zdak4izy2tnLivYlf+WlZEsJeCy05+ILVdVSqU5vnyB9",
	"YErJliDt2MZXXl0Gwva2FsxWZDDG+zaSNZxpf4VgGBMVqMYkHfC8/fbzSHA6odqsb8MfBjJRCFCYGt5I",
	"WjtrQp3IIeZMabhUth2WlmkTS51W8eOY+MbZ5fkm9A6Wt5lWVku4jeyZAeaA37KgcMGrH79zBttvKn1/",
	"Q/40Hkkl5tdm1x+TS2+1cc92Qx/gOtGGB5ulDGq1cbfLXfpKbIXQAuWij8pg7gRXi4wFqj7fMOT2weAx",
	"h4NtnjF+BZ892GD+TCtXeoIVhUTIILSafbQ6lNZG12Mm/ckYbeJWXas8Y5xUm+0n9Lk2S8E5qP//zudZ",
	"BtZWeGYttqCwlGlvMiDCEqUdYZg3wEMIlAJxv/Ms016VkKowgCiKV7nSA1kclBMrEeEf7uRAsVBqcnZ/",
	"CWrtNnRxFhFP/TNRFi6iH88TQO6cYFWyjuUFudtArMqgnNmRO4ZpHTjphK60yRkGExagR8hEEztFiw3S",
	"OQdr2RoSGRni57MXBo3wria8SaRN6ppO3M8DnS7rWsI4D/CUyTcd9QYsPRvVbCQHx/CGIWypvQvGeiPZ",
	"bqn1J2K8mpILpvCe81geuyWz8KbQFuyUJs52GTDaQRVXTNoB9FgJYxMerdE24r4qRAMtKdga+tA89BQp",
	"V0p2snQkfZhwBfenCkfShwkvDGzxUjpxg4r8IZv0wja6orRZKnZ/hohKjrq332LFlMN2KkZbDZ6wLATO",
	"fki0Sktb1LCHrESF65phOxabw367NKFOOyaHIsNyojkNDRyGe7uHq7c4O3uabMnatoxnqDZOGfO1Wb/k",
	"iZ70cLmsFaDfPTn74fE/5g8uoVWWvwr3bX/rFz5neAMwjpWI4KVc6VB0ysM11gWnMeYsKNe6Ptp0iI7h",
	"3oHBkmN3NvTHf3vLHEgpHPx92jnSc3FPLoxwImOSXPz7JwyLkdNcxdamGzysuZmOXYrVBbYfAN5xtHbR",
	"MLzkQUKDP0a4mztsP6EnbRZ3OA1JlnfEvgJUx6k7wbCvu4ERrhi2fYQ6coirmvbB4PV00HrlVcStIeHL",
	"LmWc55eSct/pS0b4riNl9CN2OGP0RiJlvy8a4foPLC8ideBPofBBOA6y+lqJzx6IaOqKL9M3jqnutPlE",
	"TASg5E64DWmgcDrpXuh4p3YTb6NTNy0GV71hqcOOMILUYTehyLmyAgtOPe1I7dsfhdRIzvvQpQ5v/gqM",
	"jPgfTxOBSzMtGWH5ypgsZ1kDG732rvCOFEZznwEnyx2WT4X3T2WaGp5p1aq25chseKunwqQ555ExU+XE",
	"ETh6ZAt7eJhRDyFO8MhwDnCiR2tX5iVYOUYcAE3/6g7qlvzVpjfpA5+Wb3pFWAdgtxuRQ+E7nAo8BPof",
	"8F9H+at2AR8DISFfnSZ3G5FtCCsDsD6UsIRxbsDabpt15HRv6wTq7n3hjUFQERMsabyq7y+zhE6o9aGX",
	"xa2ZkN5AZ1CVMZWBhPS8uHUFtMcNT76fzwctVI6YAVWykGnFLWErB6Y0SpgEIuyxBGu84GCwfWJCAifc",
	"x4eDWqf6AeP7+dMf5iPz/jhX+e2Z9SfIqrcNOuhNj+KH+MLijFivg32batgLkhHw2J+NYX/f4RjtyHtD",
	"stZw9WvicnS7BnI8dPwRGtsS25w8A7k2iX7p+uoyVIKqNapM3kn5MO8dyOtimaTk4NlCC+XqoZSFrP0S",
	"dwdLUuInPKiBsOotGLISipNcG4QR/ZZz2MH8EqYJIDlmqy7KucjSO7IR643cEevXa7AO+HR4tqORtQ9Y",
	"ZaWr8R3LgsMgZ0LSBf2o/wurfxrgG+ammc6Hc5o6jH8UtkCEBiaUV1Li5jCQOYQPLAIE9FCoQQoyB5xs",
	"BSMXUntOLuKaNtP36r16EwBHsBPKBrMgG+cKu5jNMiSfNmrOWCFmlQkf8Vqz2fYsvHk44UIXl1CeTugW",
	"jI2HO5vOp/PQbBSgWCHogj6ZzqdP6IQWzG1CHTqy18x4FTBKIFyn3nSvwkwA7SWFDbU61hZLDJT9Khou",
	"2kiorZbb+JDTLh92Sq6VBItM6NhgRm+RMY7CbPXuE4alltgC22bCMqOtJbmXThQS+jJfaZKDWaMYbQgH",
	"7uuZLrq4AIORFhGg2wjbTGMfETGFKRGrCjr/igxt9dvxbck5YYqTZ6ilIu5OE+uXjbYB5cO9sG5CtIKu",
	"ZX5tgisIQQIMuWfxdQuvn7rXoOeFqHDfpQhgtP1vAe/S90RDMus+uu4npzOEB7QTGOI/JpxAWP6TwP6m",
	"9xbweD7/3UbxNUZOTONf/wvz4mncLSWk1mrWep4ILE/GWZpnhTDJ93nOzI4uKHptLBkCy0hWPiQhO8JD",
	"bDWXeDm+iRU6MGRxFh3zrk5D5PgQ1z6Q2outwm4Tr7RllMeEK+WiX42WMvTFKPlDZG9LPRj4Xx309kER",
	"b08P99b7258wOb61xOinQTm9qvx8YCyPN1n5br6gM7q/2f8vAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
