---
openapi: 3.0.3
info:
  title: Playbook Dispatcher
  description: Playbook Dispatcher is a service for running Ansible Playbooks on hosts connected via Cloud Connector.
  version: 0.0.1
  contact:
    email: jozef@redhat.com

paths:
  /internal/dispatch:
    post:
      summary: Dispatch Playbooks
      description: Dispatches Playbooks using Cloud Connector and stores corresponding run records.
      operationId: api.internal.runs.create
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RunInput'
              minItems: 1
              maxItems: 50
      responses:
        '207':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunsCreated'

  /api/playbook-dispatcher/v1/runs:
    get:
      summary: List Playbook runs
      description: >
        Returns a list of Playbook runs for the given account.
        The list can be filtered using the `filter` parameter.
        The fields returned in the representation can be controller using `fields` parameter.
      operationId: api.runs.list
      parameters:
      - $ref: '#/components/parameters/RunsFilter'
      - $ref: '#/components/parameters/RunsFields'
      - $ref: '#/components/parameters/RunsSortBy'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Offset'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runs'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    RunId:
      description: Unique identifier of a Playbook run
      type: string
      format: uuid

    RunRecipient:
      description: Identifier of the host to which a given Playbook is addressed
      type: string
      format: uuid

    RunTimeout:
      description: Amount of seconds after which the run is considered failed due to timeout
      type: integer
      default: 3600

    Account:
      description: Identifier of the tenant
      type: string
      minLength: 1
      maxLength: 10

    Url:
      description: URL hosting the Playbook
      type: string
      format: url

    Labels:
      description: Additional metadata about the Playbook run. Can be used for filtering purposes.
      type: object
      additionalProperties:
        type: string
        default: {}

    RunStatus:
      description: Current status of a Playbook run
      type: string
      enum:
        - running
        - success
        - failure
        - timeout

    CreatedAt:
      description: A timestamp when the entry was created
      type: string
      format: date-time

    UpdatedAt:
      description: A timestamp when the entry was last updated
      type: string
      format: date-time

    Runs:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Run'
        meta:
          $ref: '#/components/schemas/Meta'
      required:
      - data
      - meta

    RunInput:
      type: object
      properties:
        recipient:
          $ref: '#/components/schemas/RunRecipient'
        account:
          $ref: '#/components/schemas/Account'
        url:
          $ref: '#/components/schemas/Url'
        labels:
          $ref: '#/components/schemas/Labels'
        timeout:
          $ref: '#/components/schemas/RunTimeout'
      required:
      - recipient
      - account
      - url

    Run:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/RunId'
        account:
          $ref: '#/components/schemas/Account'
        recipient:
          $ref: '#/components/schemas/RunRecipient'
        url:
          $ref: '#/components/schemas/Url'
        labels:
          $ref: '#/components/schemas/Labels'
        timeout:
          $ref: '#/components/schemas/RunTimeout'
        status:
          $ref: '#/components/schemas/RunStatus'
        created_at:
          $ref: '#/components/schemas/CreatedAt'
        updated_at:
          $ref: '#/components/schemas/UpdatedAt'


    RunCreated:
      type: object
      properties:
        code:
          type: integer
          example: 201
          description: status code of the request
        id:
          $ref: '#/components/schemas/RunId'
      required:
      - code

    RunsCreated:
      type: array
      items:
        $ref: '#/components/schemas/RunCreated'

    Meta:
      type: object
      additionalProperties: false
      description: Information about returned entities
      properties:
        count:
          type: integer
          description: number of results returned
          example: 50
      required:
      - count

    Error:
      type: object
      properties:
        message:
          type: string
      required:
      - message

  parameters:
    RunsFilter:
      description: Allows for filtering based on various criteria
      in: query
      name: filter
      required: false
      style: deepObject
      explode: true
      schema:
        type: object
        properties:
          status:
            type: string
            # this property should not be nullable however it is set so as a workaround for
            # https://github.com/getkin/kin-openapi/issues/293
            # ideally we would reuse '#/components/schemas/RunStatus' here
            nullable: true
            enum:
              - running
              - success
              - failure
              - timeout
          recipient:
            type: string
            # this property should not be nullable however it is set so as a workaround for
            # https://github.com/getkin/kin-openapi/issues/293
            # ideally we would reuse '#/components/schemas/RunRecipient' here
            nullable: true
            format: uuid
          # See ./internal/api/middleware/labelFilters.go
          labels:
            type: object
            # this property should not be nullable however it is set so as a workaround for
            # https://github.com/getkin/kin-openapi/issues/293
            nullable: true
            additionalProperties:
              type: string

    RunsFields:
      description: >
        Defines fields to be returned in the response.
      in: query
      name: fields
      required: false
      style: deepObject
      explode: true
      schema:
        type: object
        properties:
          data:
            type: array
            items:
              type: string
              enum:
                - id
                - account
                - recipient
                - url
                - labels
                - timeout
                - status
                - created_at
                - updated_at
            default:
              - id
              - account
              - recipient
              - url
              - labels
              - timeout
              - status

    RunsSortBy:
      description: Sort order
      in: query
      name: sort_by
      required: false
      schema:
        type: string
        enum:
          - created_at
          - created_at:asc
          - created_at:desc

    Limit:
      description: Maximum number of results to return
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 200
        default: 50

    Offset:
      in: query
      name: offset
      description: Indicates the starting position of the query relative to the complete set of items that match the query
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
