---
$id: playbookSatRunResponseMessage
$schema: http://json-schema.org/draft-07/schema#
type: object
properties:
  account:
    type: string
  request_id:
    type: string
  b64_identity:
    type: string
  upload_timestamp:
    type: string
    format: date-time
  events:
    type: array
    items:
      type: object
      properties:
        type:
          type: string
          enum: [playbook_run_update, playbook_run_finished, playbook_run_completed]
        version:
          type: integer
          minimum: 3
        correlation_id:
          type: string
          format: uuid
        sequence:
          type: integer
          minimum: 0
        host:
          type: string
        console:
          type: string
        status:
          type: string
          enum: [success, failure, canceled]
        connection_code:
          type: integer
          minimum: 0
        execution_code:
          type: integer
          minimum: 0     
        satellite_connection_code:
          type: integer
          minimum: 0
          maximum: 1
        satellite_connection_error:
          type: string
        satellite_infrastructure_code:
          type: integer
          minimum: 0
          maximum: 1
        satellite_infrastructure_error:
          type: string

      required:
        - type
        - version
        - correlation_id

required:
  - account
  - request_id
  - b64_identity
  - upload_timestamp
  - events

