
---
name: Validation

on:
- pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:12-slim

    steps:
    - uses: actions/checkout@v2
    - run: npx @stoplight/spectral lint schema/api.spec.yaml

  golang:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: insights
          POSTGRES_USER: insights
          POSTGRES_PASSWORD: insights
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - run: go build .
    - run: go vet .

    - name: download go-migrate
      run: curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz

    - run: CLOWDER_ENABLED=false make test

    - name: test down migrations
      run: make migrate-db-undo
