
---
name: Validation

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: npm i -g @stoplight/spectral
    - run: spectral lint schema/api.spec.yaml
